# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '10.13'
inhibit_all_warnings!


target 'MyUtils' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  
use_frameworks!
pod 'ReactiveObjC', '~> 2.1.0'
  
end
